#+title: selected-window-accent-mode
#+author: James Dyer
#+options: toc:nil author:t title:t num:t
#+startup: showall

#+TOC: headlines 2 local

* Summary

The Selected Window Accent Mode is an Emacs package designed to visually distinguish the currently selected window by applying a unique accent colour to its fringes, mode line, header line, and margins.

* Installation

** use-package (emacs 29)

Put the following into your emacs init file:

#+begin_src elisp
(use-package selected-window-accent-mode
  :defer t
  :vc (:fetcher github :repo "captainflasmr/selected-window-accent-mode"))
#+end_src

** use-package (MELPA)

- TODO

** from source

Download the `.el` file and place it in your Emacs `load-path`. Then either manually load it or add it to your configuration to be loaded at startup.

#+begin_src elisp
(require 'selected-window-accent-mode)
#+end_src

* Usage

Toggle the mode on and off with =M-x selected-window-accent-mode=

* Customization

** Accent Color

You can invoke =selected-window-accent= with a custom color if you want to temporarily set a different accent color:

#+begin_src elisp
(selected-window-accent "#ff6699")
#+end_src

You can also modify the =selected-window-accent= function to adjust the accent algorithm according to your needs.

** Fringes, Mode Line, and Header Line

If you want different properties for the fringes, mode line, header line, or the margins, you can directly edit the =set-face-attribute= and =set-window-margins= calls within the =selected-window-accent= and =reset-window-accent= functions respectively.

* Minor Mode

#+begin_src elisp
(define-minor-mode selected-window-accent-mode
...
)
#+end_src

The =selected-window-accent-mode= is a global minor mode that you can toggle to enable or disable the accenting of the selected window. When enabled, it distinguishes the selected window with a special accent color.

* Functions

** selected-window-accent

This is the main function that applies the accent color to the selected window.

#+begin_src elisp
(defun selected-window-accent (&optional custom-accent-colour)
#+end_src

- *custom-accent-colour*: An optional parameter to specify a custom accent color as a string (e.g., `"#ff6699"`). If not provided, it defaults to the background color of the *highlight* face attribute.

** reset-window-accent

Resets all windows to their default accent colors.

#+begin_src elisp
(defun reset-window-accent ()
#+end_src

* Variables

** selected-window-accent-mode

A mode variable for the =selected-window-accent-mode=. Set to `nil` to disable by default.

#+begin_src elisp
(defvar selected-window-accent-mode nil
  "Mode variable for `selected-window-accent-mode'.")
#+end_src

* Hooks

Two hooks are used to automatically update the window accents when the window configuration or state changes:

- window-configuration-change-hook
- window-state-change-hook

These are added when the =selected-window-accent-mode= is enabled and removed when disabled.

* Example

To enable the accent mode automatically upon starting Emacs, add the following line to your `.emacs` or `init.el` file:

#+begin_src elisp
(selected-window-accent-mode 1)
#+end_src

This will activate the selected window accenting each time Emacs starts.

* BUGS

Fix these to get to a tagged Version 0.1

In order of priority

- TODO (selected-window-accent-mode 1) not working in init file needs to be manually run
- DOING improve documentation
- TODO careful with removing header-line on all windows for example magit commit window and probably some others may needs to add some logic depending on mode
- TODO header-line not shown on window split
- TODO when first built and installed we get the following errors
#+begin_src
In selected-window-accent:
selected-window-accent-mode.el:18:2: Warning: docstring wider than 80 characters
selected-window-accent-mode.el:35:24: Warning: reference to free variable ‘visual-fill-column-mode’
selected-window-accent-mode.el:59:20: Warning: defcustom for ‘selected-window-accent-mode’ fails to specify containing group

In end of data:
selected-window-accent-mode.el:36:21: Warning: the function ‘visual-fill-column-mode’ is not known to be defined.
selected-window-accent-mode.el:25:14: Warning: the function ‘color-darken-name’ is not known to be defined.
selected-window-accent-mode.el:24:12: Warning: the function ‘color-desaturate-name’ is not known to be defined.
#+end_src
- TODO am I happy with the name of this package?
- TODO add to MELPA

* roadmap

** TODO define custom variables:

- accent thickness
- face name colour
- accent configuration (to set individually)
  - all
  - left
  - right
  - modeline
  - fence
- saturation adjustment
- darken adjustment
- hue adjustment

** TODO define your own colour

Currently the default is to use the =highlight= face

** TODO accent presents

- =tiling= - :top:right:bottom:left: - accent thickness modeline - to provide a tiling window complete outline experience
- =simple= - :bottom: - full height modeline
- =subtle= - :left:
- =default= - :top:right:bottom:left: - full height modeline

  by default this package when enabled is currently set effectively to =tiling= (mainly because I currently use a tiling window manager)
