#+title: TODO selected-window-accent-mode
#+author: James Dyer
#+options: toc:nil author:nil title:nil num:nil tasks:todo
#+startup: showall

* ____________________ roadmap ____________________

** DOING add to MELPA
** TODO Incorporate =mode-line-active= and =mode-line-inactive= somehow as this would make more sense especially in the 'default mode.
** TODO highlight selected tab with same accent color?
** TODO header-line not shown on window split - I have a funny feeling this could be very difficult, if not impossible!
** TODO restore modeline height when switching between modes
** TODO adjust the not selected-window margin to avoid little window navigation. disruption, hence translating a fringe pixel width to a number of margin characters, not quite sure how I am going to do this yet.
** TODO excess selected-window disruption in header-line. (not sure I can do much about this)
** TODO define more custom variables:
- accent color saturation adjustment
- accent color darken adjustment
- accent color hue adjustment
- compensating margin
** TODO define which theme face attribute to use as the main accent color
Currently the default is to use the =highlight= face
** WATCH possible overheads of updating visual elements for each window?
** WATCH careful with removing header-line on all windows, for example magit commit window and probably some others may need to add some logic depending on mode.
